### ISSUE TITLE
[Feature Request] Drag and drop attachments into the conversation preview on the left and have them queue for that conversation

### ISSUE THREAD

**Issue by CSab6482** [sgtaziz/WebMessage#112]

**Comment by sgtaziz** [comment]
Unfortunately this won't be possible for a few reasons.
Mainly, due to the Chat and Messages components being split up, with a subcomponent for uploading attachments. Some serious changes would need to happen for this, and maybe not the prettiest. Unfortunately I do not think it is worth the effort at the time 😢

**Comment by CSab6482** [comment]
That's okay!
