### ISSUE TITLE
[Feature Request] iOS 16 Comptaibility

### ISSUE THREAD

**Issue by ml-dp** [sgtaziz/WebMessage#200]
iOS version: 16.3.1 (mine specifically but for others it would be helpful to have compatibility that is up to date with palera1n compatibility]
Jailbreak: palera1n-c
Tweak Version: 0.7.0

I was using WebMessage heavily when I was on iOS 14. After updating to palera1n, iOS 16, this tweak no longer works. I recently saw you are active here, and I really really really hope you are able to make it compatible with iOS 16. I would be incredibly grateful and this is the only tweak that makes me want to jailbreak since I do not rely on my phone heavily, and would rather respond quickly from my laptop. 

I do know I can use Intel Unison, however with Intel Unison, it requires Windows 11. My laptop is not compatible with Windows 11, so I am stuck on Windows 10. 

I am willing to test on my phone if you do like me to test things out.

**Comment by TempAccountNull** [comment]
@sgtaziz Looks like we got another tester.
@cafelinked Please be advised, If we were to even think of updating to anything higher than ios 14 then it will break the application on anything lower than ios 15. They completely changed the way the framework works in future iOS's as it's incompatible in it's current state as of why you're crashing.

**Comment by sgtaziz** [comment]
This would require update to the tweak component. I would love to pick this project back up, but it's extremely difficult to develop blind and rely on testers without a jailbreakable device.
If I get the chance, I would definitely pick it up again. Otherwise, until then, the tweak source code is open (WebMessage-Tweak repo on my github). Anyone is welcome to try and update the new framework definitions.

**Comment by bgktmxg** [comment]
@cafelinked You may want to consider doing what I do and get a dedicated phone to run WebMessage. It shouldn't need a SIM, you just set up Text Message Forwarding between it and your main iPhone.

Any iPhone 6 will do, as they maxed out at iOS 13.

@sgtaziz I have a stack of old iPhone's running various different software versions. I would be more than happy to test if you decide to pick this back up in the future.

**Comment by ml-dp** [comment]
@sgtaziz @TempAccountNull I see. I wish I could understand the coding. I know basics of HTML, CSS, python and Lua along with basic commands to run on Linux and Windows for debug. I could try to understand, with trial and error. But I would probably break the code more as I have no in-depth knowledge as you both.

@bgktmxg Hm. That is another option. It would be a last resort option for sure.

**Comment by ml-dp** [comment]
I'll close this for now. In the meanwhile, I will take a look at your code, will fork it and see how far I can go. Though, any development with testing will likely take years (which by the time it is released, someone may have already done it) as I give dedicated half-hour/day towards anything related to coding.

Thank you both for your time!

**Comment by ariankordi** [comment]
Just thought I'd chime in here in case anyone is interested.
I'm trying to port the tweak to rootless iOS 15, mostly everything Just Works(TM) after changing some paths to be rootless-friendly, with some exceptions:
* On iOS 15 (rootful or rootless) sending an attachment crashes the server:
```
2024-01-14 16:25:53.863618-0500 WebMessage[1904:31701] *** Terminating app due to uncaught exception 'MRYIPCException', reason: 'callExternalMethod:withArguments:completion: - Failed to lookup service port: Unknown service name'
*** First throw call stack:
(0x180abfc60 0x1982ebee4 0x1010c59e8 0x1010c6424 0x18077f094 0x180780094 0x18072673c 0x1807271f4 0x180730ec8 0x1dbee0e00 0x1dbee092c)
libc++abi: terminating with uncaught exception of type NSException
Process 1904 stopped
* thread #11, queue = 'com.muirey03.libmryipc-messageQueue', stop reason = signal SIGABRT
    frame #0: 0x00000001bb37fbbc libsystem_kernel.dylib`__pthread_kill + 8
```

* Conversion from HEIC/HEVC doesn't seem to work, printing the following:
```
[WebMessage] handle_write_error:107: stream error
[WebMessage] imagePNG_write_error_break:84: *** ERROR: imagePNG_write_error_break
[WebMessage] handle_write_error:107: No IDATs written into file
```
* For whatever reason, on meowbrek2, daemons aren't allowed to access sms.db (I can't even access it from SSH whatsoever), which causes the server to just not work on that jailbreak (doesn't happen with palera1n). However, running it in Filza works??

Finally I noticed that this is made to be built with Mac, which is too bad because I don't have one right now and have had to rely on Theos and hex-editing the Swift binary.


If anyone's interested in helping me then let me know. I may publish a fork soon but I haven't played around with it enough.
